source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Desavio_appprova' do

    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'AlamofireImage'
    pod 'RealmSwift'
    pod 'SVProgressHUD'

end
